-- Write your PostgreSQL query statement below
SELECT E1.EMPLOYEE_ID
FROM EMPLOYEES E1
WHERE E1.SALARY < 30000
AND E1.MANAGER_ID IS NOT  NULL
AND NOT EXISTS (SELECT EMPLOYEE_ID FROM EMPLOYEES E2 WHERE E2.EMPLOYEE_ID = E1.MANAGER_ID  )
ORDER BY EMPLOYEE_ID
